spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USER:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      client-type: lettuce
  profiles:
    default: prod
  cache:
    redis:
      key-prefix: service-discovery
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9094}
server:
  port: 8080
  address: 0.0.0.0